- name: Vérifier si k3s-agent est déjà installé
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin

- name: Rejoindre le cluster k3s en tant que worker
  shell: >
    curl -sfL https://get.k3s.io | K3S_URL=https://192.168.1.28:6443
    K3S_TOKEN={{ hostvars['192.168.1.28']['k3s_node_token'] }} sh -s - agent
  when: not k3s_bin.stat.exists

- name: S'assurer que k3s-agent est démarré et activé
  systemd:
    name: k3s-agent
    enabled: yes
    state: started
